### ISSUE TITLE
TypeError: ctx.onerror is not a function

### ISSUE THREAD

**Issue by und3fined** [koajs/koa#1186]
Environment
- Nodejs: 8.11.1
- Koa: 2.5.1

```
const onerror = err => ctx.onerror(err);
                               ^

TypeError: ctx.onerror is not a function
    at Array.onerror (./server/node_modules/koa/lib/application.js:147:32)
    at listener (./server/node_modules/on-finished/index.js:169:15)
    at onFinish (./server/node_modules/on-finished/index.js:100:5)
    at callback (./dist/server/node_modules/ee-first/index.js:55:10)
    at ServerResponse.onevent (./server/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:111:20)
    at ServerResponse.emit (events.js:208:7)
    at onFinish (_http_outgoing.js:720:10)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

How to fix it?
- Replace: `const onerror = err => ctx.onerror(err);`
- With: `const onerror = ctx.onerror;`

~~*paragraph removed by fl0w*~~

**Comment by fl0w** [comment]
Could you provide a full minimal reproducible example showcasing how this occurs?

**Comment by angelbeltran** [comment]
Having the same issue.
- Nodejs v8.9.4
- Koa 2.5.1

**Comment by angelbeltran** [comment]
I found out what my problem was. I was using

```
const Koa = require('koa');
const bodyParser = require('koa-bodyparser');
const app = new Koa();

// I forgot to call the bodyParser module...
// app.use(bodyParser);

// better :)
app.use(bodyParser());
```

**Comment by und3fined** [comment]
This is bug with `bodyParser`(koa-bodyparser) =))

**Comment by HongYangHT** [comment]
I get the same error and fixed it with `app.use(bodyParser())`

**Comment by RoadAspen** [comment]
I get the same error too and fixed it with `app.use(bodyParser())`

**Comment by eason-shsf** [comment]
> I found out what my problem was.
> 
> ```
> const Koa = require('koa');
> const bodyParser = require('koa-bodyparser');
> const app = new Koa();
> 
> // I forgot to call the bodyParser module...
> // app.use(bodyParser);
> 
> // better :)
> app.use(bodyParser());
> ```
> 
> @und3fined perhaps this or something like this was your issue?

saved my ass

**Comment by Jay2983** [comment]
resolved with app.use(bodyParser());
