### ISSUE TITLE
Error when a function instead of a generator is passed into use

### ISSUE THREAD

**Issue by xixixao** [koajs/koa#120]
Given

``` javascript
var koa = require('koa');
var app = koa();

app.use(function () {
  this.body = 'Hello World';
});

app.listen(3000);
```

(Note missing asterisk after `function` keyword) errors out with rather unhelpful:

```
Error: yield a function, promise, generator, array, or object
    at next (/koatest/node_modules/koa/node_modules/co/index.js:84:10)
    at Object.<anonymous> (/koatest/node_modules/koa/node_modules/co/index.js:91:5)
    at next (/koatest/node_modules/koa/node_modules/co/index.js:74:19)
    at /koatest/node_modules/koa/node_modules/co/index.js:91:5
    at Server.<anonymous> (/koatest/node_modules/koa/lib/application.js:102:22)
    at Server.EventEmitter.emit (events.js:101:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:505:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:358:22)
    at Socket.EventEmitter.emit (events.js:98:17)
```

A side-question: When there is no `yield` in the middleware, should **koa**, and similar frameworks, require a generator?

**Comment by lbeschastny** [comment]
But why ordinary functions are not allowed in `koa`?

There is no real difference between an ordinary function and non-yielding generator function in this context.

**Comment by jonathanong** [comment]
it's mostly so that developers don't get confused when they put a regular function instead of a generator function, especially when generators when new.

this restriction will eventually be removed, but for now, you can try doing `app.experimental=true`, which removes this restriction. https://github.com/koajs/koa/issues/415
