### ISSUE TITLE
'next is not a function' in middleware

### ISSUE THREAD

**Issue by Stormcore** [koajs/koa#1215]
Hello all, I have an issue when trying to add Sequelize DB to state of ctx:

add-db-to-state.js
```js
const db = require('../libs/db');

const logger = require('../helpers/get-logger')(__filename);

const addPostgreSQLToState = () => async (ctx, next) => {
  logger.debug('addDBToState');

  const connection = await db.getConnection();

  ctx.state.db = connection;

  await next();
};

module.exports = addPostgreSQLToState;
```

app.js
```js
const addDBToState = require('./middlewares/add-db-to-state');
...
app.use(addDBToState());
...
```

Log I get:

```
[2018-07-10T17:16:22.582Z] [error] /src/middlewares/errors.js - errors - path=/auth/user/, state=[Circular], message=next is not a function, stack=TypeError: next is not a function
    at initialize (/node_modules/passport/lib/middleware/initialize.js:53:5)
    at dispatch (/node_modules/koa-compose/index.js:42:32)
    at /home/.../src/middlewares/add-db-to-state.js:12:9
    at process._tickCallback (internal/process/next_tick.js:68:7) 
[2018-07-10T17:16:22.583Z] [info] /src/middlewares/requests.js - response - status=500, time=13ms, body={ username: qoqoqoq13311, email: qweqwe@aa.aa11, fullName: qweqweqweqweq, passwordConfirmation: qweqqweq } 

```

**Comment by fl0w** [comment]
There’s insufficient information to solve this riddle as an outsider. To my eyes everything looks correct with respect Koa. The only think that comes to mind is that the error origins elsewhere.

I’m on a plane but can take another peak once I get to a computer.

**Comment by Stormcore** [comment]
It was an issue with ordinary passport, koa-passport library solved the inconsistency
