### ISSUE TITLE
2.8.0 can not start  Application this.keys=option.keys | undefined raise error

### ISSUE THREAD

**Issue by huo4444** [koajs/koa#1377]
2.8.0 can not start  Application this.keys=option.keys | undefined raise error

**Comment by huo4444** [comment]
D:\work\projects\qm-common-server\node_modules\koa\lib\application.js:53
    this.keys = options.keys || undefined;
              ^
TypeError: Cannot set property keys of #<Application> which has only a getter
    at new Application (D:\work\projects\qm-common-server\node_modules\koa\lib\application.js:53:15)
    at new EggCore (D:\work\projects\qm-common-server\node_modules\egg-core\lib\egg.js:44:5)
    at new EggApplication (D:\work\projects\qm-common-server\node_modules\egg\lib\egg.js:42:5)
    at new Application (D:\work\projects\qm-common-server\node_modules\egg\lib\application.js:59:5)
    at Object.<anonymous> (D:\work\projects\qm-common-server\node_modules\egg-cluster\lib\app_worker.js:13:13)

**Comment by aijun198600** [comment]
The same problem...

**Comment by chenbin92** [comment]
Fixed： https://github.com/koajs/koa/commit/287e589ac773d3738b2aa7d40e0b6d43dde5261b

**Comment by huo4444** [comment]
can you push a new release to npm repo  ?

**Comment by dead-horse** [comment]
2.8.1 already released.
