### ISSUE TITLE
Properties do not seem to be working with ctx.throw

### ISSUE THREAD

**Issue by rkoziel** [koajs/koa#1542]
Hello, I am trying to use the properties parameter with ctx.throw but I do not see the object added anywhere in the response. For example, if part of a request message is missing, I want to do something like the following:
```javascript
if (!username) {
    return ctx.throw(400, 'Invalid request message', {
        validationErrors: {
            username: 'Username cannot be null',
        },
    });
}
```
When I try to do a console.log of the response, I see the status and message set properly but I do not see the validationErrors object in the response. Any suggestions on this are appreciated.

**Comment by miwnwski** [comment]
It's not an error with Koa but they way an error object is stringified.
Maybe this little example will help you:

```js
const Koa = require('koa')
const app = new Koa()

app.use(async (ctx, next) => {
  try {
    await next()
  } catch (err) {
    console.error(err)
    throw err
  }
})

app.use(async ctx => {
  ctx.throw(400, 'invalid request', {
    errors: [{name:'SomeName'}]
  })
})

app.listen(3000)
```

```sh
$ curl localhost:3000
BadRequestError: invalid request
    at Object.throw (/Users/miwnwski/src/koajs/issue-1542/node_modules/koa/lib/context.js:97:11)
    at /Users/miwnwski/src/koajs/issue-1542/index.js:14:11
    at dispatch (/Users/miwnwski/src/koajs/issue-1542/node_modules/koa-compose/index.js:42:32)
    at /Users/miwnwski/src/koajs/issue-1542/index.js:6:9
    at dispatch (/Users/miwnwski/src/koajs/issue-1542/node_modules/koa-compose/index.js:42:32)
    at /Users/miwnwski/src/koajs/issue-1542/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/Users/miwnwski/src/koajs/issue-1542/node_modules/koa/lib/application.js:168:12)
    at Server.handleRequest (/Users/miwnwski/src/koajs/issue-1542/node_modules/koa/lib/application.js:150:19)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12) {
  errors: [ { name: 'SomeName' } ]
}
```
