### ISSUE TITLE
Package subpath './lib/request' is not defined by "exports" in node_modules/koa/package.json

### ISSUE THREAD

**Issue by kookxiang** [koajs/koa#1589]
may related to https://github.com/koajs/koa/commit/acb08e0f192fb2692e5dbb6d80dcffd101f2a41c

from https://github.com/eggjs/egg-core/
```
Uncaught Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/request' is not defined by "exports" in /.../node_modules/egg-core/node_modules/koa/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:491:3)
    at resolveExports (internal/modules/cjs/loader.js:444:36)
    at Module._findPath (internal/modules/cjs/loader.js:484:31)
    at Module._resolveFilename (internal/modules/cjs/loader.js:818:27)
    at Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at (/code/node_modules/_egg-core@4.20.0@egg-core/lib/loader/mixin/extend.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
```

**Comment by Lxxyx** [comment]
Related: https://github.com/nodejs/node/pull/34718
Solution: Upgrade Node.js version >= 12.20

**Comment by Artoria-0x04** [comment]
Using node v17.1.0, still has this problem.
