### ISSUE TITLE
npm install cannot find koa

### ISSUE THREAD

**Issue by mickeyvip** [koajs/koa#169]
Failing to install with node `0.10.24` and `0.11.9`

```
$ npm install koa
npm http GET https://registry.npmjs.org/koa
npm http 304 https://registry.npmjs.org/koa
npm http GET https://registry.npmjs.org/koa/-/koa-0.2.1.tgz
npm http 404 https://registry.npmjs.org/koa/-/koa-0.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/koa/-/koa-0.2.1.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:117:20)
npm ERR!     at fs.js:1596:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "koa"
npm ERR! cwd /Users/me/Projects/nodejs/koa_test
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/me/Projects/nodejs/koa_test/npm-debug.log
npm ERR! not ok code 0
```

```
$ npm install koa
npm http GET https://registry.npmjs.org/koa
npm http 304 https://registry.npmjs.org/koa
npm http GET https://registry.npmjs.org/koa/-/koa-0.2.1.tgz
npm http 404 https://registry.npmjs.org/koa/-/koa-0.2.1.tgz
npm ERR! fetch failed https://registry.npmjs.org/koa/-/koa-0.2.1.tgz
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/fetch.js:57:12)
npm ERR!     at WriteStream.EventEmitter.emit (events.js:120:20)
npm ERR!     at fs.js:1569:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:97:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "koa"
npm ERR! cwd /Users/me/Projects/nodejs/koa_test
npm ERR! node -v v0.11.9
npm ERR! npm -v 1.3.15
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/me/Projects/nodejs/koa_test/npm-debug.log
npm ERR! not ok code 0
```

**Comment by sunfeng90** [comment]
After  I`npm install  koa` or `cnpm install koa -g`,but output not found!
