### ISSUE TITLE
Problem with async generators

### ISSUE THREAD

**Issue by vtambourine** [koajs/koa#584]
I have a problem running async/await code in babel 6 environment.
Here is problematic code:

```js
require('babel-polyfill');

function getValues() {
  return Promise.resolve([1,2,3,4]);
}

async function foo() {
  var values = await getValues();
  console.log(values);
}
```

I expect it to write `[1, 2, 3, 4]` in the console. However, it results in error:
```
$ babel-node test.js
TypeError: Object.setPrototypeOf called on null or undefined
    at Function.setPrototypeOf (native)
    at runtime.mark (/Users/benjamin/.nvm/versions/node/v4.1.1/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:111:14)
    ...
```

I tried to precompile it and run by `node` itself. This results in different error:
```
$ node test-transpiled.js
/Users/benjamin/Projects/test-transpiled.js:4
  var _marked = [foo].map(regeneratorRuntime.mark);
                          ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/benjamin/Projects/test-transpiled.js:4:27
    ...
```

My environments are: `babel 6.0.15 (babel-core 6.0.16)`, `node v4.1.1`.

**Comment by vtambourine** [comment]
Ooops, wrong tab...
