### ISSUE TITLE
Using Koa 2 with Babel 6 / Next is not a function

### ISSUE THREAD

**Issue by 0x80** [koajs/koa#585]
I just started playing with Koa2 in combination with Babel 6 and it seems like somehow things get messed up. With this function

```javascript 
// logger
app.use(async (ctx, next) => {
  const start = new Date()
  await next()
  const ms = new Date() - start
  console.log(`${ctx.method} ${ctx.url} - ${ms}`)
})
```

I get the following error

```
TypeError: next is not a function
      at _callee$ (server.js:16:9)
      at tryCatch (/Users/me/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:61:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/me/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:334:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/me/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/regenerator/runtime.js:94:21)
      at step (/Users/me/Development/dagr/server.js:25:273)
      at /Users/me/Development/dagr/server.js:25:443
      at new Promise (/Users/me/.npm-packages/lib/node_modules/babel-cli/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:182:7)
      at /Users/me/Development/dagr/server.js:25:99
      at server.js:19:2
      at dispatch (/Users/me/Development/dagr/node_modules/koa/node_modules/koa-compose/index.js:41:32)
      at next (/Users/me/Development/dagr/node_modules/koa/node_modules/koa-compose/index.js:42:18)
      at /Users/me/Development/dagr/node_modules/koa-66/index.js:130:41
      at dispatch (/Users/me/Development/dagr/node_modules/koa/node_modules/koa-compose/index.js:41:32)
      at /Users/me/Development/dagr/node_modules/koa/node_modules/koa-compose/index.js:34:12
      at Server.<anonymous> (/Users/me/Development/dagr/node_modules/koa/lib/application.js:119:7)
      at emitTwo (events.js:87:13)
```

My babelrc is 
```javascript
{
  "presets": ["react", "es2015", "stage-0"]
}
```

Any idea what might be going wrong?

**Comment by gyson** [comment]
I guess it's a issue about babel 6. Did you try babel 5 ?

**Comment by 0x80** [comment]
I ran into other issues with babel 6 as well. Haven't tried 5 with this setup. Will do that tonight (CET)

**Comment by omsmith** [comment]
Which version of Babel6. Expect that would be fixed as of 6.0.14

**Comment by 0x80** [comment]
I have things working now with the latest versions. I think there were some conflicting versions because I was starting my app with `nodemon server.js --exec babel-node` which used my globally installed babel-node and not the one I had updated locally to my project.

So now using `nodemon server.js --exec ./node_modules/.bin/babel-node`

**Comment by promag** [comment]
@0x80 Can you post your `.babelrc` and babel version? Thanks.

**Comment by stojanovic** [comment]
@0x80 add `nodemon server.js --exec babel-node` to package.json scripts as "start" and run it as `npm start` :) It should run a version from `node_modules/.bin`.

**Comment by 0x80** [comment]
Yes that was my intention also. Was debugging using the commands directly and fiddling with preset flag. But thanks anyway :)

**Comment by 0x80** [comment]
@promag sure

```
{
  "presets": ["react", "es2015", "stage-0"]
}
```
`babel-cli..........................................[6.1.1]`
