### ISSUE TITLE
Error thrown twice

### ISSUE THREAD

**Issue by dacodekid** [koajs/koa#600]
Is this expected behavior?

```javascript
const Koa = require('koa');
const app = new Koa();

app.use((ctx, next) => {
  throw new Error();
});

app.listen(3000);
```

```sh
  Error
      at one.js:6:9
      at dispatch (/Users/dacodekid/dev/koa-hpa/node_modules/koa-compose/index.js:41:32)
      at /Users/dacodekid/dev/koa-hpa/node_modules/koa-compose/index.js:34:12
      at Server.<anonymous> (/Users/dacodekid/dev/koa-hpa/node_modules/koa/lib/application.js:126:7)
      at emitTwo (events.js:87:13)
      at Server.emit (events.js:172:7)
      at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:527:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)


  Error
      at one.js:6:9
      at dispatch (/Users/dacodekid/dev/koa-hpa/node_modules/koa-compose/index.js:41:32)
      at /Users/dacodekid/dev/koa-hpa/node_modules/koa-compose/index.js:34:12
      at Server.<anonymous> (/Users/dacodekid/dev/koa-hpa/node_modules/koa/lib/application.js:126:7)
      at emitTwo (events.js:87:13)
      at Server.emit (events.js:172:7)
      at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:527:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
```

**Comment by gyson** [comment]
I guess there are two requests and one of them is `/favicon.ico`.

**Comment by dacodekid** [comment]
@gyson. Thx :) That's the issue.
