### ISSUE TITLE
a promise was created in a  handler but was not returned from it

### ISSUE THREAD

**Issue by christiansakai** [koajs/koa#607]
Hello,

I am trying to use Koa with MongooseJS.

here is the MongooseJS code
```
export function* update(next) {
  this.response.body = yield Item
    .findById(this.params.id).exec()
    .then(item => {
      const updated = _.merge(item, this.request.body);
      return updated.save();
    });
}
```

Seems like I'm missing something obvious but I don't know what is it.

**Comment by jonathanong** [comment]
what's the error?

**Comment by christiansakai** [comment]
Ah, sorry forgot to write the error

```
Warning: a promise was created in a  handler but was not returned from it
    at Query.exec (/Users/christiansakai/Desktop/cs/node_modules/mongoose/lib/query.js:2125:10)
    at Object.update$ (/Users/christiansakai/Desktop/cs/common/api/item/item.controller.js:24:31)
    at tryCatch (/Users/christiansakai/Desktop/cs/node_modules/regenerator/runtime.js:61:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/christiansakai/Desktop/cs/node_modules/regenerator/runtime.js:328:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/christiansakai/Desktop/cs/node_modules/regenerator/runtime.js:94:21)
    at Object.dispatch (/Users/christiansakai/Desktop/cs/node_modules/koa-router/lib/router.js:331:14)
    at [object Generator].next (native)
    at Object.proxy (/Users/christiansakai/Desktop/cs/node_modules/koa-proxy/index.js:25:23)
    at [object Generator].next (native)
    at Object.bodyParser (/Users/christiansakai/Desktop/cs/node_modules/koa-bodyparser/index.js:68:12)
    at [object Generator].next (native)
    at onFulfilled (/Users/christiansakai/Desktop/cs/node_modules/koa/node_modules/co/index.js:65:19)
    at processImmediate [as _immediateCallback] (timers.js:374:17)
From previous event:
    at next (/Users/christiansakai/Desktop/cs/node_modules/koa/node_modules/co/index.js:100:51)
    at onFulfilled (/Users/christiansakai/Desktop/cs/node_modules/koa/node_modules/co/index.js:69:7)
    at /Users/christiansakai/Desktop/cs/node_modules/koa/node_modules/co/index.js:54:5
From previous event:
    at Object.co (/Users/christiansakai/Desktop/cs/node_modules/koa/node_modules/co/index.js:50:10)
    at Object.createPromise (/Users/christiansakai/Desktop/cs/node_modules/koa/node_modules/co/index.js:30:15)
    at Server.<anonymous> (/Users/christiansakai/Desktop/cs/node_modules/koa/lib/application.js:132:8)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:521:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
```

**Comment by dead-horse** [comment]
looks like the error was thrown by `mongoose` ? I'm not familiar with `mongoose`. :(

**Comment by juliangruber** [comment]
seems to me as well that mongoose or the use thereof is the problem

**Comment by meehow** [comment]
This is new [bluebird](https://github.com/petkaantonov/bluebird) feature (mongoose is using it).
http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-none-were-returned-from-it

**Comment by meehow** [comment]
Looks like it was a bug in bluebird@3.0.5
it's fixed in bluebird@3.0.6

**Comment by christiansakai** [comment]
thanks! it is fine now!

**Comment by tj** [comment]
whoop!
