### ISSUE TITLE
`this.message` containing line breaks

### ISSUE THREAD

**Issue by halt-hammerzeit** [koajs/koa#682]
Today i tried to send `this.message` containing line breaks and it only sent the part before the first line break.
Can this possibly be an issue in Koa?
If not then it may be another code.

**Comment by halt-hammerzeit** [comment]
`this.body = '...'` works.

```
Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:311:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
From previous event:
    at Object._callee9$ (web server.js:845:21)
    at tryCatch (G:\work\webapp\node_modules\babel-runtime\regenerator\runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (G:\work\webapp\node_modules\babel-runtime\regenerator\runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (G:\work\webapp\node_modules\babel-runtime\regenerator\runtime.js:121:21)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
    at [object Generator].next (native)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
    at [object Generator].next (native)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
    at [object Generator].next (native)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
    at [object Generator].next (native)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
    at [object Generator].next (native)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
    at [object Generator].next (native)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
    at [object Generator].next (native)
    at Object.<anonymous> (G:\work\webapp\node_modules\koa-mount\index.js:52:26)
```

`this.message = '...'` doesn't

```Parse Error```

**Comment by halt-hammerzeit** [comment]
Maybe it's a special error handling case for `this.message` because the `Error: ` part also vanished.

**Comment by PlasmaPower** [comment]
Hmm, I'm not sure where koa is doing this. Can you confirm that https://nodejs.org/api/http.html#http_response_statusmessage works when used outside of koa?

**Comment by halt-hammerzeit** [comment]
`this.res.statusMessage` gives me the same bug.
I guess it's Node then.

**Comment by juliangruber** [comment]
I'm quite sure the http spec doesn't allow new lines in its status message
